GET http://localhost:9999/api/v1/task
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODA2MzIyMDQsInVzZXJJZCI6MTAwfQ.MFUiCrm62X8EVvfnBagyQXe3jSx0SAtgAh7wP3TAGZ4

###
GET http://localhost:9999/api/v1/task/40
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNTQ

###
POST http://localhost:9999/api/v1/task
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODA2MzIyMDQsInVzZXJJZCI6MTAwfQ.MFUiCrm62X8EVvfnBagyQXe3jSx0SAtgAh7wP3TAGZ4

{
  "description": "task description 444",
  "date": "2019-01-01T00:00:00Z"
}